### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelection' of undefined

### ISSUE THREAD

**Issue by htekgulds** [Trudko/advanced-new-file#16]
[Enter steps to reproduce below:]

1. Press Ctrl + Alt + N

**Atom Version**: 0.192.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [advanced-new-file](https://github.com/Trudko/advanced-new-file) package, v0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelection' of undefined

```
At /C:/Users/Hasan/.atom/packages/advanced-new-file/lib/advanced-new-file-view.coffee:326

TypeError: Cannot read property 'getSelection' of undefined
  at AdvancedFileView.module.exports.AdvancedFileView.attach (C:\Users\Hasan\.atom\packages\advanced-new-file\lib\advanced-new-file-view.coffee:206:9)
  at AdvancedFileView.module.exports.AdvancedFileView.toggle (C:\Users\Hasan\.atom\packages\advanced-new-file\lib\advanced-new-file-view.coffee:9:3)
  at atom-workspace.<anonymous> (C:\Users\Hasan\.atom\packages\advanced-new-file\lib\advanced-new-file-view.coffee:9:3)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Hasan\AppData\Local\atom\app-0.192.0\resources\app\src\command-registry.js:238:29)
  at C:\Users\Hasan\AppData\Local\atom\app-0.192.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Hasan\AppData\Local\atom\app-0.192.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Hasan\AppData\Local\atom\app-0.192.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Hasan\AppData\Local\atom\app-0.192.0\resources\app\src\window-event-handler.js:180:20)

```

### Commands

```
     -0:03.5 advanced-new-file:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "solarized-dark-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
achievements, v0.7.1
advanced-new-file, v0.4.0
autocomplete-plus, v2.11.0
emmet, v2.3.7
language-docker, v1.1.3
seti-ui, v0.6.3
terminal-status, v1.6.4

# Dev
No dev packages
```

**Comment by Trudko** [comment]
Hi, thank you. I will take a look at this this week.

**Comment by htekgulds** [comment]
No problem :) Keep up the great work!

21 Nis 2015 Sal, 11:20 tarihinde, Trudko <notifications@github.com> şunu
yazdı:

**Comment by Trudko** [comment]
Are you able to reproduce this consistently?

**Comment by htekgulds** [comment]
Actually no I can't. It might me a combination of other circumstances maybe but idk for sure.

**Comment by Trudko** [comment]
@htekgulds Ok if this happens again let me know.

**Comment by Trudko** [comment]
I will close it for now. If this happens again please let me know.
