### ISSUE TITLE
Uncaught TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by csaket** [Trudko/advanced-new-file#42]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [advanced-new-file](https://github.com/Trudko/advanced-new-file) package, v0.4.3

### Stack Trace

Uncaught TypeError: Cannot read property 'message' of undefined

```
At D:\Users\asiddiqui\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:56

TypeError: Cannot read property 'message' of undefined
  at ErrorView.module.exports.ErrorView.initialize (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:56:21)
  at ErrorView.View (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new ErrorView (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\error-view.js:14:46)
  at D:\Users\asiddiqui\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\updates-panel.js:84:44
  at Emitter.module.exports.Emitter.emit (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:579:27)
  at D:\Users\asiddiqui\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:303:17
  at D:\Users\asiddiqui\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:326:20
  at exit (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:59:16)
  at triggerExitCallback (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -2:46.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-redeye-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "deprecation-cop",
      "atom-beautify",
      "atom-sharp",
      "tabularize",
      "tabular",
      "git-diff"
    ],
    "themes": [
      "redeye-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-runner, v2.4.1
atom-yeoman, v0.3.11
command-toolbar, v1.0.12
highlight-selected, v0.10.1
language-sql-mysql, v0.3.1
language-thrift, v1.0.1
linter, v1.2.3
minimap, v4.11.2
minimap-highlight-selected, v4.3.0
omnisharp-atom, vundefined
open-recent, v2.3.0
pretty-json, v0.4.1
redeye-ui, v0.5.0
Sublime-Style-Column-Selection, v1.3.0
view-tail-large-files, v0.2.0

# Dev
No dev packages
```

**Comment by Trudko** [comment]
Hi :) please  take a look at https://github.com/Osmose/advanced-open-file, it replaces this project which I can't maintain anymore. Thank you for understanding :)
