### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by csaket** [Trudko/advanced-new-file#49]
[Enter steps to reproduce below:]

1. Try to update linter

**Atom Version**: 1.0.19
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [advanced-new-file](https://github.com/Trudko/advanced-new-file) package, v0.5.0

### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'grim'

Error: Cannot find module 'grim'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.activate (A:\Apps\.atom\packages\linter\lib\main.coffee:5:5)
  at Package.module.exports.Package.activateNow (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:245:19)
  at D:\Users\asiddiqui\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:226:30
  at Package.module.exports.Package.measure (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:169:15)
  at Package.module.exports.Package.activate (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:218:14)
  at PackageManager.module.exports.PackageManager.activatePackage (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:486:21)
  at D:\Users\asiddiqui\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-manager.js:313:60
  at exit (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (D:\Users\asiddiqui\AppData\Local\atom\app-1.0.19\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
     -1:39.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:39.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:29.4.0 application:show-settings (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "deprecation-cop",
      "atom-sharp",
      "tabular",
      "git-diff"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
command-toolbar, v1.0.12
highlight-selected, v0.10.1
language-sql-mysql, v0.3.1
language-thrift, v1.0.1
linter, v1.8.1
minimap, v4.13.4
minimap-highlight-selected, v4.3.1
navigate, v0.1.10
omnisharp-atom, v0.24.14
open-recent, v2.3.0
pretty-json, v0.4.1
rest-client, v0.4.0
Sublime-Style-Column-Selection, v1.3.0
view-tail-large-files, v0.2.1

# Dev
No dev packages
```

**Comment by Trudko** [comment]
Hi please used advanced open file package.
