### ISSUE TITLE
Uncaught TypeError: atom.workspace.getActiveTextEditor(...).getSelection is not a function

### ISSUE THREAD

**Issue by adrenalinkyo** [Trudko/advanced-new-file#52]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.3
**Thrown From**: [advanced-new-file](https://github.com/Trudko/advanced-new-file) package, v0.5.0

### Stack Trace

Uncaught TypeError: atom.workspace.getActiveTextEditor(...).getSelection is not a function

```
At /Users/madnomad/.atom/packages/advanced-new-file/lib/advanced-new-file-view.coffee:276

TypeError: atom.workspace.getActiveTextEditor(...).getSelection is not a function
    at AdvancedFileView.module.exports.AdvancedFileView.attach (/Users/madnomad/.atom/packages/advanced-new-file/lib/advanced-new-file-view.coffee:276:56)
    at AdvancedFileView.module.exports.AdvancedFileView.toggle (/Users/madnomad/.atom/packages/advanced-new-file/lib/advanced-new-file-view.coffee:295:8)
    at atom-workspace.<anonymous> (/Users/madnomad/.atom/packages/advanced-new-file/lib/advanced-new-file-view.coffee:76:73)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -0:58 tree-view:toggle (atom-text-editor.editor.is-focused)
     -0:45.8.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:40.9.0 find-and-replace:find-next (atom-text-editor.editor.is-focused)
     -0:32.7.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:29.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:29.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:25.7.0 core:undo (atom-text-editor.editor.is-focused)
     -0:24.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:22.6.0 core:undo (atom-text-editor.editor.is-focused)
     -0:22.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:15.2.0 advanced-new-file:toggle (atom-text-editor.editor.is-focused)
     -0:05.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:05.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:02.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:02.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 advanced-new-file:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "power-mode",
      "remote-sync"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "advanced-new-file": {
    "caseSensitiveAutoCompletion": true,
    "createFileInstantly": true,
    "showFilesInAutoComplete": true,
    "suggestCurrentFilePath": true,
    "addTextFromSelection": true
  }
}
```

### Installed Packages

```coffee
# User
advanced-new-file, v0.5.0
file-type-icons, v0.7.4
language-blade, v0.16.0
minimap, v4.18.2
navigation-history, v0.1.8
remote-edit, v1.8.23

# Dev
No dev packages
```

**Comment by iamstarkov** [comment]
use advanced-open-file instead

**Comment by iamstarkov** [comment]
this should be closed. @Trudko what do you think about closing issues? as far as project abandoned

**Comment by Trudko** [comment]
@iamstarkov definitely.
