### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by RyanMacG** [Trudko/advanced-new-file#9]
[Enter steps to reproduce below:]

1. Press CMD+ALT+N

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: [advanced-new-file](https://github.com/Trudko/advanced-new-file) package, v0.3.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:61

TypeError: undefined is not a function
  at splitKeyPath (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:61:31)
  at Object.plus.valueForKeyPath (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:410:14)
  at Config.module.exports.Config.getRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:590:19)
  at Config.module.exports.Config.get (/Applications/Atom.app/Contents/Resources/app/src/config.js:179:21)
  at AdvancedFileView.module.exports.AdvancedFileView.attach (/Users/ryanmacg/Dropbox/.atom/packages/advanced-new-file/lib/advanced-new-file-view.coffee:211:20)
  at AdvancedFileView.module.exports.AdvancedFileView.toggle (/Users/ryanmacg/Dropbox/.atom/packages/advanced-new-file/lib/advanced-new-file-view.coffee:231:8)
  at atom-workspace.<anonymous> (/Users/ryanmacg/Dropbox/.atom/packages/advanced-new-file/lib/advanced-new-file-view.coffee:34:73)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:172:20)

```

### Commands

```
     -1:21.0 editor:move-to-end-of-screen-line (atom-text-editor.editor)
  4x -1:17.1 core:move-down (atom-text-editor.editor)
 13x -1:16.5 core:move-up (atom-text-editor.editor)
  3x -0:45.9 core:move-left (atom-text-editor.editor)
  7x -0:45.4 core:move-right (atom-text-editor.editor)
  3x -0:44.3 core:select-left (atom-text-editor.editor)
  2x -0:42.3 core:backspace (atom-text-editor.editor)
     -0:41.6 core:save (atom-text-editor.editor)
     -0:40.7 editor:move-to-end-of-screen-line (atom-text-editor.editor)
  3x -0:39.9 core:move-down (atom-text-editor.editor)
     -0:37.6 advanced-new-file:toggle (atom-text-editor.editor)
 12x -0:36.5 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:24.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.9 advanced-new-file:toggle (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack.remove)
     -0:01.5 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:01.5 AtomPair:hide views (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "advanced-new-file": {
    "suggestCurrentFilePath": true
  }
}
```

### Installed Packages

```coffee
# User
advanced-new-file, v0.3.2
atom-pair, v0.35.0
autocomplete-plus, v2.1.6
block-travel, v1.0.2
color-picker, v1.4.4
command-logger, v0.22.0
dash, v1.0.2
editor-stats, v0.17.0
file-icons, v1.4.10
git-tab-status, v1.5.3
html2haml, v0.6.0
language-haml, v0.15.0
language-latex, v0.4.1
language-nginx, v0.4.0
language-rspec, v0.3.0
language-slim, v0.3.0
latex, v0.18.1
linter, v0.11.1
linter-rubocop, v0.2.1
linter-ruby, v0.1.4
monokai, v0.12.0
motepair, v0.14.0
package-sync, v0.1.2
pain-split, v1.3.1
rsense, v0.6.0
rspec-snippets, v0.4.0
ruby-slim, v0.2.0
ruby-strftime-reference, v0.2.0
set-syntax, v0.2.1
tabs-to-spaces, v0.8.1
tabular, v0.1.0
visual-bell, v1.0.0

# Dev
No dev packages
```

It seems to still work it just throws this error every time I go to create a new one.

**Comment by Trudko** [comment]
@RyanMacG  thank you I will take a look at it tomorrow.

**Comment by Trudko** [comment]
I've updated the version please take a look.

**Comment by RyanMacG** [comment]
0.3.3 seems to have resolved it, thanks!

**Comment by Trudko** [comment]
Thank you! :)

**Comment by pcbulai** [comment]
1. CMD+N

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [advanced-new-file](https://github.com/Trudko/advanced-new-file) package, v0.4.3


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/paulbulai/.atom/packages/advanced-new-file/lib/advanced-new-file-view.coffee:231

TypeError: undefined is not a function
  at AdvancedFileView.module.exports.AdvancedFileView.attach (/Users/paulbulai/.atom/packages/advanced-new-file/lib/advanced-new-file-view.coffee:231:56)
  at AdvancedFileView.module.exports.AdvancedFileView.toggle (/Users/paulbulai/.atom/packages/advanced-new-file/lib/advanced-new-file-view.coffee:250:8)
  at atom-workspace.<anonymous> (/Users/paulbulai/.atom/packages/advanced-new-file/lib/advanced-new-file-view.coffee:48:73)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -5:39.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -5:35.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:35.5.0 status-bar:toggle (atom-text-editor.editor)
     -5:31.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -5:28.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:28.7.0 status-bar:toggle (atom-text-editor.editor)
     -5:24.4.0 settings-view:open (atom-text-editor.editor.is-focused)
     -5:08.3.0 core:close (div.settings-view.pane-item)
     -5:07.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -5:07.3.0 pane:show-previous-item (atom-text-editor.editor.mini.is-focused)
     -5:04.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:04.1.0 editor-stats:toggle (atom-text-editor.editor)
     -0:02.9.0 advanced-new-file:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {},
  "advanced-new-file": {
    "showFilesInAutoComplete": true,
    "addTextFromSelection": true
  }
}
```

### Installed Packages

```coffee
# User
advanced-new-file, v0.4.3
angularjs, v0.3.0
atom-alignment, v0.12.1
css-comb, v2.1.1
editor-stats, v0.17.0
editorconfig, v1.0.0
emmet, v2.3.10
gist-it, v0.7.0
git-log, v0.4.1
jsformat, v0.9.0
jshint, v1.3.7
project-manager, v1.15.10

# Dev
No dev packages
```

**Comment by Volox** [comment]
Same problem in 0.4.3

**Comment by eboracus** [comment]
Got this same error in 0.4.3 as well. Looks to me like it is due to the 'Add Text From Selection' settings option. With this on I get this error thrown (tried in buffers with and without any text just in case) and off everything works fine.

**Comment by DjebbZ** [comment]
Same than above. I have the same the error from 0.4.3 only when "Add Text From Selection" is checked. Otherwise all good. 
Also, the checked option doesn't work. The problem is that if I have some text selected and the option checked, this selected text isn't used at all for the name of the new file.

**Comment by Trudko** [comment]
Hi guys sorry these days I don't have much time if anybody want to take a look I am happy to merge pull request.
